# Generated by Django 5.0.4 on 2024-05-03 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_comment_created_on_post_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
